apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
  - name: junk
    image: busybox:1.28
    args:
    - sleep
    - "9999"
  securityContext:
    sysctls:
    - name: kernel.shm_next_id
      value: "4"