version: 2
mergeable:
  # - when: issues.opened
  #   validate:
  #     - do: description
  #       must_include:
  #         regex: '(?<=### Kubernetes Platform\n\n)AKS'
  #   pass:
  #     - do: labels
  #       add: AKS
  - when: issues.opened
    validate:
      - do: description
        must_include:
          regex: '(?<=### Kubernetes Platform\n\n)GKE'
    pass:
      - do: labels
        add: GKE
#backup
  # - when: issues.opened
  #   validate:
  #     - do: contents
  #       must_include:
  #         regex: '/(?<=### Kubernetes Platform\n\n)GKE/gm'
  #   pass:
  #     - do: labels
  #       add: GKE
