version: 2
mergeable:
  - when: issues.opened
    name: Label GKE
    validate:
      - do: description
        must_include:
          regex: '(?<=### Kubernetes Platform\n\n)GKE'
    pass:
      - do: labels
        add: GKE

  - when: issues.opened
    name: label AKS
    validate:
      - do: description
        must_include:
          regex: '(?<=### Kubernetes Platform\n\n)AKS'
    pass:
      - do: labels
        add: AKS
