version: 2
mergeable:
  - when: issues.opened
    name: Label validate
    validate:
      - do: description
        must_include:
          regex: '### Kyverno Rule Type\n\nValidate'
    pass:
      - do: labels
        add: validation

  - when: issues.opened
    name: Label mutate
    validate:
      - do: description
        must_include:
          regex: '### Kyverno Rule Type\n\nMutate'
    pass:
      - do: labels
        add: mutation

  - when: issues.opened
    name: Label generate
    validate:
      - do: description
        must_include:
          regex: '### Kyverno Rule Type\n\nGenerate'
    pass:
      - do: labels
        add: generation

  - when: issues.opened
    name: Label imageVerify
    validate:
      - do: description
        must_include:
          regex: '### Kyverno Rule Type\n\nimageVerify'
    pass:
      - do: labels
        add: imageVerify