version: 2
mergeable:
  - when: issues.opened
    validate:
      - do: title
        begins_with:
          match: ['BUG']
    pass:
      - do: labels
        add: 'bug'
  - when: issues.opened
    validate:
      - do: title
        begins_with:
          match: ['FEATURE']
    pass:
      - do: labels
        add: 'feature'