apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  securityContext:
    runAsNonRoot: true
  initContainers:
  - name: initjunk
    image: busybox:1.28
    args:
    - sleep
    - "9999"
    # securityContext:
    #   allowPrivilegeEscalation: true
  containers:
  - name: junk
    image: busybox:1.28
    args:
    - sleep
    - "9999"
    # securityContext:
    #   allowPrivilegeEscalation: false
    #   runAsNonRoot: false
