name: "Bug Report: CLI"
description: Report a bug in the Kyverno CLI.
title: "[Bug] "
labels: ["bug", "cli"]
body:
  - type: markdown
    attributes:
      value: |
        Please tell us about the bug.
  - type: dropdown
    id: kyverno-version
    attributes:
      label: Kyverno Version
      description: What version of Kyverno are you running?
      options:
        - 1.4.x
        - 1.5.x
        - 1.6.x
    validations:
      required: true
  - type: dropdown
    id: k8s-version
    attributes:
      label: Kubernetes Version
      description: What version of Kubernetes are you running?
      options:
        - 1.20.x
        - 1.21.x
        - 1.22.x
        - 1.23.x
    validations:
      required: true
  - type: dropdown
    id: k8s-platform
    attributes:
      label: Kubernetes Platform
      description: What platform of Kubernetes are you running?
      options:
        - EKS
        - GKE
        - AKS
        - KinD
        - Minikube
        - K3d
        - OpenShift
        - Other (please tell us)
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Kyverno logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true