blank_issues_enabled: false
contact_links:
  - name: Kyverno policy request
    url: https://github.com/kyverno/policies/issues/new?assignees=&labels=&template=sample_policy.md&title=
    about: Open an issue to request a new policy.
  - name: Kyverno Community Support (#kyverno channel on Kubernetes Slack) 
    url: https://kubernetes.slack.com/archives/CLGR9BJU9
    about: Please ask and answer any Kyverno usage questions here.
  - name: Kyverno Contributor Discussions
    url: https://github.com/kyverno/kyverno/discussions
    about: Please ask and answer questions regarding Kyverno internals here.
