name: "Sample Policy"
description: Suggest a new policy that you would like Kyverno to support. This issue type is not for problems with existing policies.
title: "[Sample] "
labels: ["sample"]
body:
  - type: markdown
    attributes:
      value: |
        Please tell us about the sample policy you wish to see.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem.
      placeholder: A clear and concise description of the problem statement.
      # value: "asdf"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution Description
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
      # value: "asdf"
    validations:
      required: true
  - type: textarea
    id: bug-expectations
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      # placeholder: Tell us what you see!
      # value: "asdf"
    validations:
      required: true
  - type: textarea
    id: good
    attributes:
      label: Example "good" resource.
      description: >-
        Provide an example of a "good" Kubernetes resource which, if the request is for a validate rule, should be allowed.
        For other types of policies, provide a sample input resource.
      render: yaml
  - type: textarea
    id: logs
    attributes:
      label: Kyverno logs
      description: >-
        Please copy and paste any relevant log output.
        This will be automatically formatted into code, so no need for backticks.
        For help on how to view Pod logs in Kubernetes, see [here](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#examine-pod-logs).
      render: shell
  - type: input
    id: slack
    attributes:
      label: Slack discussion
      description: >-
        If this issue is the result of a discussion thread on Slack, please provide the link to the discussion for reference.
      # placeholder: ex. email@example.com
    validations:
      required: false
  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting
      description: >-
        By submitting this issue, you agree that you have performed some basic attempts at researching and solving your problem.
      options:
        - label: I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
          required: true
        - label: I have searched other issues in this repository and mine is not recorded.
          required: true