apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-capabilities-strict
  annotations:
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Adding capabilities other than `NET_BIND_SERVICE` is disallowed. In addition,
      all containers must explicitly drop `ALL` capabilities. Needs
      Kyverno 1.6.0 for the AnyNotIn operator.
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: require-drop-all
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: >-
          Containers must drop `ALL` capabilities.
        deny:
          conditions:
            any:
            - key: "{{ request.object.spec.[ephemeralContainers, initContainers, containers][].securityContext.capabilities.drop[?contains(@, 'ALL')][] | length(@) }}"
              operator: NotEquals
              value: "{{ request.object.spec.[ephemeralContainers, initContainers, containers][] | length(@) }}"    
    - name: disallow-adding-capabilities-strict
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: >-
          Any capabilities added other than NET_BIND_SERVICE are disallowed.
        deny:
          conditions:
            all:
            - key: "{{ request.object.spec.[ephemeralContainers, initContainers, containers][].securityContext.capabilities.add[] }}"
              operator: AnyNotIn
              value:
              - NET_BIND_SERVICE
