apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-volume-types
  annotations:
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod,Volume
    pod-policies.kyverno.io/autogen-controllers: none
    kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.22"
    policies.kyverno.io/description: >-
      In addition to restricting HostPath volumes, the restricted pod security profile
      limits usage of non-core volume types to those defined through PersistentVolumes.
      This policy blocks a number of different non-core volume types as named.
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: restricted-volumes-pods
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: >-
        Any of the following volume types are restricted and may not be used: gcePersistentDisk,
        awsElasticBlockStore, gitRepo, nfs, iscsi, glusterfs, rbd, flexVolume, cinder, cephfs,
        flocker, fc, azureFile, vsphereVolume, quobyte, azureDisk, portworxVolume, scaleIO,
        storageos, and photonPersistentDisk.
      deny:
        conditions:
          all:
          - key: "{{ request.object.spec.volumes[].keys(@)[] }}"
            operator: AnyIn
            value:
            - gcePersistentDisk
            - awsElasticBlockStore
            - gitRepo
            - nfs
            - iscsi
            - glusterfs
            - rbd
            - flexVolume
            - cinder
            - cephfs
            - flocker
            - fc
            - azureFile
            - vsphereVolume
            - quobyte
            - azureDisk
            - portworxVolume
            - scaleIO
            - storageos
            - photonPersistentDisk
  - name: restricted-volumes-controllers
    match:
      resources:
        kinds:
        - Deployment
        - DaemonSet
        - StatefulSet
        - Job
    validate:
      message: >-
        Any of the following volume types are restricted and may not be used: gcePersistentDisk,
        awsElasticBlockStore, gitRepo, nfs, iscsi, glusterfs, rbd, flexVolume, cinder, cephfs,
        flocker, fc, azureFile, vsphereVolume, quobyte, azureDisk, portworxVolume, scaleIO,
        storageos, and photonPersistentDisk.
      deny:
        conditions:
          all:
          - key: "{{ request.object.spec.template.spec.volumes[].keys(@)[] }}"
            operator: AnyIn
            value:
            - gcePersistentDisk
            - awsElasticBlockStore
            - gitRepo
            - nfs
            - iscsi
            - glusterfs
            - rbd
            - flexVolume
            - cinder
            - cephfs
            - flocker
            - fc
            - azureFile
            - vsphereVolume
            - quobyte
            - azureDisk
            - portworxVolume
            - scaleIO
            - storageos
            - photonPersistentDisk
  - name: restricted-volumes-cronjob
    match:
      resources:
        kinds:
        - CronJob
    validate:
      message: >-
        Any of the following volume types are restricted and may not be used: gcePersistentDisk,
        awsElasticBlockStore, gitRepo, nfs, iscsi, glusterfs, rbd, flexVolume, cinder, cephfs,
        flocker, fc, azureFile, vsphereVolume, quobyte, azureDisk, portworxVolume, scaleIO,
        storageos, and photonPersistentDisk.
      deny:
        conditions:
          all:
          - key: "{{ request.object.spec.jobTemplate.spec.template.spec.volumes[].keys(@)[] }}"
            operator: AnyIn
            value:
            - gcePersistentDisk
            - awsElasticBlockStore
            - gitRepo
            - nfs
            - iscsi
            - glusterfs
            - rbd
            - flexVolume
            - cinder
            - cephfs
            - flocker
            - fc
            - azureFile
            - vsphereVolume
            - quobyte
            - azureDisk
            - portworxVolume
            - scaleIO
            - storageos
            - photonPersistentDisk