name: Policy Test

on:
  push:
    branches:
      - master
      - main
      - release*
  pull_request:
    branches:
      - main
      - release*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Get Kyverno
        run: |
          git clone https://github.com/kyverno/kyverno
      
      - name: Set up Go
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.5
        with:
          go-version: 1.17

      - name: Cache Go modules
        uses: actions/cache@d9747005de0f7240e5d35a68dca96b3f41b8b340 # v1.2.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Print dir structure
        run: ls -lahF

      - name: Test
        run: |
          go run kyverno/cmd/cli/kubectl-kyverno/main.go test .

      - name: Kyverno test
        run: kyverno test .
